### ISSUE TITLE
Allow Workflow automation to run in sequential or parallel excuition

### ISSUE THREAD

**Issue by viane** [IBM/ibm_zos_zosmf#99]
Looks like the current logic is that if the workflow allows parallel execution, the ansible-playbook will default to parallel automation, and no way to override with the setting.

Looking for a parameter to specify what style of automation the playbook is to execute the workflow steps.

```yaml
    - name: "zOSMF workflow"
      delegate_to: localhost
      ibm.ibm_zosmf.zmf_workflow:
        ...
        state: "started"
        action "start | startParallel" # <- example parameter
        workflow_owner: "xxxx"
        ...
        workflow_vars_file: "wf-var.properties "
      register: result
```
